name:                BattleshipServer
version:             0.1.0.0
license:             BSD3

extra-source-files:
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.7

library:
  source-dirs: src

executables:
  BattleshipServer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BattleshipServer

tests:
  BattleshipServer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BattleshipServer
